In [1]:
from model import *
from data import *

## Train your Unet with membrane data
membrane data is in folder membrane/, it is a binary classification task.

The input shape of image and mask are the same :(batch_size,rows,cols,channel = 1)

### Train with data generator

In [2]:
# data_gen_args = dict(rotation_range=0.2,
#                     width_shift_range=0.05,
#                     height_shift_range=0.05,
#                     shear_range=0.05,
#                     zoom_range=0.05,
#                     horizontal_flip=True,
#                     fill_mode='nearest')
# myGene = trainGenerator(2,'data/membrane/sample_data','image','label',data_gen_args,save_to_dir = None)
data_gen_args = dict(rotation_range=0.2,
                    width_shift_range=0.05,
                    height_shift_range=0.05,
                    shear_range=0.05,
                    zoom_range=0.05,
                    horizontal_flip=True,
                    fill_mode='nearest')
myGene = trainGenerator(1,'data/membrane/sample_data','image','label',data_gen_args,save_to_dir = None)
model = unet()
model_checkpoint = ModelCheckpoint('unet_new2.hdf5', monitor='loss',verbose=1, save_best_only=True)
model.fit_generator(myGene,steps_per_epoch=2000,epochs=5,callbacks=[model_checkpoint])
# model.fit_generator(myGene,steps_per_epoch=500,epochs=5,callbacks=[model_checkpoint])

Found 30 images belonging to 1 classes.
Found 30 images belonging to 1 classes.


C:\Users\user\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)
C:\Users\user\AppData\Local\Temp\ipykernel_4344\3370111213.py:19: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(myGene,steps_per_epoch=2000,epochs=5,callbacks=[model_checkpoint])


img.shape (2, 256, 256, 3)
Epoch 1/5
img.shape (2, 256, 256, 3)
   2/2000 [..............................] - ETA: 1:23:06 - loss: 0.7949 - accuracy: 0.2291img.shape (2, 256, 256, 3)


KeyboardInterrupt: 

### Train with npy file

In [2]:
# model = unet()
# model_checkpoint = ModelCheckpoint('unet_my_model.hdf5', monitor='loss',verbose=1, save_best_only=True)
# imgs_train,imgs_mask_train = geneTrainNpy("data/membrane/train/aug/","data/membrane/train/aug/")
# model.fit(imgs_train, imgs_mask_train, batch_size=2, epochs=10, verbose=1,validation_split=0.2, shuffle=True, callbacks=[model_checkpoint])

C:\Users\user\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Epoch 1/10


ValueError: in user code:

    File "C:\Users\user\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\user\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\user\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\user\anaconda3\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\user\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\user\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 277, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer "model" "                 f"(type Functional).
    
    Input 0 of layer "conv2d" is incompatible with the layer: expected axis -1 of input shape to have value 3, but received input with shape (2, 256, 256, 1)
    
    Call arguments received by layer "model" "                 f"(type Functional):
      • inputs=tf.Tensor(shape=(2, 256, 256, 1), dtype=float32)
      • training=True
      • mask=None


### test your model and save predicted results

In [2]:
testGene = testGenerator("data/membrane/test_data")
# testGene = testGenerator("data/membrane/test")
model = unet()
model.load_weights("unet_new2.hdf5")
# print("model",model.summary())
results = model.predict_generator(testGene,10,verbose=1)
print(results[0],'\n')
# results = results*255
# print(results[0])
saveResult("data/membrane/test_result4",results)

C:\Users\user\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)
C:\Users\user\AppData\Local\Temp\ipykernel_11776\2254383389.py:6: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  results = model.predict_generator(testGene,10,verbose=1)


10/10 [==============================] - 7s 744ms/step


Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
C:\Users\user\Desktop\FYP\Image-to-Image-Translation-Models-An-AI-Approach-towards-Immunostaining\data.py:125: UserWarning: data/membrane/test_result4\1_predict.png is a low contrast image
  io.imsave(os.path.join(save_path,"%d_predict.png"%i),img)
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint

[[[0.90044206 0.91782767 0.9266987 ]
  [0.9836016  0.9577248  0.97549516]
  [0.9903275  0.9725366  0.98874587]
  ...
  [0.9886939  0.9623881  0.9879557 ]
  [0.94622505 0.92844236 0.9669993 ]
  [0.92369795 0.87883854 0.9293328 ]]

 [[0.98091435 0.9589078  0.96887624]
  [0.9929302  0.976406   0.9949439 ]
  [0.9978496  0.99076855 0.9983699 ]
  ...
  [0.99326074 0.9913803  0.9977694 ]
  [0.97921944 0.9816215  0.9949817 ]
  [0.9709113  0.9548339  0.98593473]]

 [[0.994188   0.9854614  0.99039733]
  [0.998503   0.99158984 0.99821705]
  [0.9994957  0.9973211  0.99944156]
  ...
  [0.99933076 0.99811375 0.9993836 ]
  [0.99588317 0.9969265  0.9980283 ]
  [0.9953669  0.9907426  0.9955535 ]]

 ...

 [[0.9956337  0.9832175  0.9907585 ]
  [0.99929637 0.9954177  0.9983458 ]
  [0.99964    0.9975381  0.9992764 ]
  ...
  [0.94724685 0.7175326  0.9234284 ]
  [0.94756365 0.7101787  0.9295681 ]
  [0.9166279  0.7681043  0.91336006]]

 [[0.98889667 0.96165824 0.97486186]
  [0.99821955 0.9850679  0.9964368 ]


In [13]:
print(type(results))

NameError: name 'results' is not defined